//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueStatsTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueStatsTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;metadata&quot;: {
        ///      &quot;dataVersion&quot;: &quot;2&quot;,
        ///      &quot;matchId&quot;: &quot;EUW1_5682340554&quot;,
        ///      &quot;participants&quot;: [
        ///        &quot;ndlLvHpXhTM3GApnGt2UtytZ_2PG9l7UyGhmPqESQCL8GG0I2B5R_R6zXheLJoEt8UrKledrSxECTQ&quot;,
        ///        &quot;ECot_iDNovn-00LFm0tl8ps0m8eVziYK0tftxsJvz-gX8a6qhxNIXa9b56E34NhLeKRO0U5WlkxCyQ&quot;,
        ///        &quot;88rWPxkPl0YiRPyDk2s7Cl_Dp-dBeI2mtzUtc3cRwh0fmU8ZmeAhY04Rz00qUY56wPKp3T8jR9QfSw&quot;,
        ///        &quot;_5g35rrt5H2CPnPvbFfwTzFjGBY7XL88KMQEVfQxW9kQV9Q5nb1XCCheaOC27GV7dYUpCZxWQyECKg&quot;,
        ///        &quot;DQ-pz54bwcAhq6LxqRDoLU7052_hgEIxG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatchDataTest1_WinsLast10Games {
            get {
                return ResourceManager.GetString("MatchDataTest1_WinsLast10Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;metadata&quot;: {
        ///      &quot;dataVersion&quot;: &quot;2&quot;,
        ///      &quot;matchId&quot;: &quot;EUW1_5682340554&quot;,
        ///      &quot;participants&quot;: [
        ///        &quot;ndlLvHpXhTM3GApnGt2UtytZ_2PG9l7UyGhmPqESQCL8GG0I2B5R_R6zXheLJoEt8UrKledrSxECTQ&quot;,
        ///        &quot;ECot_iDNovn-00LFm0tl8ps0m8eVziYK0tftxsJvz-gX8a6qhxNIXa9b56E34NhLeKRO0U5WlkxCyQ&quot;,
        ///        &quot;88rWPxkPl0YiRPyDk2s7Cl_Dp-dBeI2mtzUtc3cRwh0fmU8ZmeAhY04Rz00qUY56wPKp3T8jR9QfSw&quot;,
        ///        &quot;_5g35rrt5H2CPnPvbFfwTzFjGBY7XL88KMQEVfQxW9kQV9Q5nb1XCCheaOC27GV7dYUpCZxWQyECKg&quot;,
        ///        &quot;DQ-pz54bwcAhq6LxqRDoLU7052_hgEIxG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatchDataTest2_WinsLast10Games {
            get {
                return ResourceManager.GetString("MatchDataTest2_WinsLast10Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;metadata&quot;: {
        ///      &quot;dataVersion&quot;: &quot;2&quot;,
        ///      &quot;matchId&quot;: &quot;EUW1_5682340554&quot;,
        ///      &quot;participants&quot;: [
        ///        &quot;ndlLvHpXhTM3GApnGt2UtytZ_2PG9l7UyGhmPqESQCL8GG0I2B5R_R6zXheLJoEt8UrKledrSxECTQ&quot;,
        ///        &quot;ECot_iDNovn-00LFm0tl8ps0m8eVziYK0tftxsJvz-gX8a6qhxNIXa9b56E34NhLeKRO0U5WlkxCyQ&quot;,
        ///        &quot;88rWPxkPl0YiRPyDk2s7Cl_Dp-dBeI2mtzUtc3cRwh0fmU8ZmeAhY04Rz00qUY56wPKp3T8jR9QfSw&quot;,
        ///        &quot;_5g35rrt5H2CPnPvbFfwTzFjGBY7XL88KMQEVfQxW9kQV9Q5nb1XCCheaOC27GV7dYUpCZxWQyECKg&quot;,
        ///        &quot;DQ-pz54bwcAhq6LxqRDoLU7052_hgEIxG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatchDataTest3_WinsLast10Games {
            get {
                return ResourceManager.GetString("MatchDataTest3_WinsLast10Games", resourceCulture);
            }
        }
    }
}
